# Python Basics: A Short Review

As you may remember, Python is built around a rich ecosystem of libraries.  
Typically, the required libraries are imported at the top of a file—either from the standard library, from third-party packages, or from code you have written yourself.

Throughout this course, we will rely on a small and well-defined set of libraries.  
Before installing and using many third-party packages, I strongly recommend becoming familiar with the capabilities of Python’s **standard library** (https://docs.python.org/3/library/), which already provides a wide range of useful functionality.

The following modules are required for this tutorial:

In [1]:
import pathlib
import numpy as np
from matplotlib import pyplot as plt

The statement `import ...` specifies which library is loaded.  
Using `as` assigns an alias to the library name, which can reduce typing in the code.

There are widely accepted standard abbreviations (e.g. `numpy as np`, `matplotlib.pyplot as plt`).  
However, aliases should be used with moderation, as excessive abbreviations can reduce code readability.

Modern editors provide powerful autocomplete functionality, so typing speed is rarely the bottleneck in programming.

## Below is a brief review of concepts covered in COMP208.

In [2]:
x = 2  # variable definition
y = 3  # variable definition
print(x + y)  # x plus y
print(x - y)  # x subtract y
print(x / y)  # x divided by y
print(pow(x, y))  # x to the power of y
print(x**y)  # x to the power of y
print(x + y, end='\n\n')
print(x + y)

5
-1
0.6666666666666666
8
8
5

5


## Don't define your constants, but use numpy:
Basic np commands
https://numpy.org/doc/stable/reference/routines.math.html

In [5]:
print(np.pi)  # pi = 3.14159
print(np.sqrt(x))  # square root of x
print(np.exp(y))  # exp(y)
print(np.sin(np.pi / y))  # sin(pi / y)
print(np.arcsin(np.sin(np.pi / y)))
print(np.deg2rad(90))  # deg to rad
print(np.rad2deg(np.pi / 2))  # rad to deg
print(np.round([0.34, 0.57], decimals=1))  # round
print(np.floor(np.sqrt(x)))  # floor
print(np.ceil(np.sqrt(x)))  # ceil
print(np.trunc(np.sqrt(x)))  # trunc
xp = np.array([1, 2])
yp = np.array([5, 6])
print(np.interp(1.5, xp, yp))  # interpolate

3.141592653589793
1.4142135623730951
20.085536923187668
0.8660254037844386
1.0471975511965976
1.5707963267948966
90.0
[0.3 0.6]
1.0
2.0
1.0
5.5


## Basic logic and if-else statements

In [6]:
a = 4
b = 7

if a < b:
    print('a is less than b')
elif (a == b):
    print('a equals b')
else:
    print('a is greater than b')

if not (a < b):
    print('a is not less than b')
    

c = 5
if a == c:
    print('a equals c')
else:
    print('a does not equal c')

if a != c:
    print('a does not equal c')

a is less than b
a does not equal c
a does not equal c


## for loops

In [3]:
N = 5
a = 0
x = np.zeros(N,)  # preallocate space
print(x)
for i in range(N):
    a = a + i
    x[i] = 2**i

print(a, end='\n\n')
print(x, end='\n\n')
print(x.shape, end='\n\n')

[0. 0. 0. 0. 0.]
10

[ 1.  2.  4.  8. 16.]

(5,)



notice that x is a (N,) array, not a (1, N) array (i.e., not a 1 x N matrix)

In [4]:
a = 0
x = np.zeros((N, 1))  # preallocate space
print(x)
for i in range(N):
    a = a + i
    x[i, :] = 2**i

print(a, end='\n\n')
print(x, end='\n\n')
print(x.shape, end='\n\n')

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
10

[[ 1.]
 [ 2.]
 [ 4.]
 [ 8.]
 [16.]]

(5, 1)



Notice that x is not a (N,) array, it is a (N, 1) array (i.e., is a N x 1 matrix)

In [5]:
y = x.copy()  # Copy x
y = y[::-1, :]  # Flip the data in the (N, 1) array
print(y, end='\n\n')
print(y.shape, end='\n\n')

a = 0
x = np.zeros((1, N))  # preallocate space
print(x)
for i in range(N):
    a = a + i
    x[:, i] = 2**i

print(a, end='\n\n')
print(x, end='\n\n')
print(x.shape, end='\n\n')



[[16.]
 [ 8.]
 [ 4.]
 [ 2.]
 [ 1.]]

(5, 1)

[[0. 0. 0. 0. 0.]]
10

[[ 1.  2.  4.  8. 16.]]

(1, 5)



Notice that x is not a (N,) array, it is a (1, N) array (i.e., is a 1 x N matrix)

In [6]:
x = x.ravel()

Ravel converts the 2D (1, N) array into a 1D (N,) array

## while loops

In [ ]:
b = 1
tol = 1e-3
i = 0
while b > tol:
    b = b / 2
    i += 1

print('Number of iterations to reach b = ', b, ' is ', i)

Number of iterations to reach b =  0.0009765625  is  10
[1.000000e+00 5.000000e-01 2.500000e-01 1.250000e-01 6.250000e-02
 3.125000e-02 1.562500e-02 7.812500e-03 3.906250e-03 1.953125e-03
 9.765625e-04]
Number of iterations to reach b =  0.0009765625  is  10 



Same while loop but just storing each iterate in an array

In [7]:
b = [1]  # list, because we will use "append", which is only lists
tol = 1e-3
i = 0
while b[i] > tol:
    b.append(b[i] / 2)  # here we are using append
    i += 1  # increment counter
b = np.array(b)  # convert from list to array (numpy array)
print(b)
print('Number of iterations to reach b = ', b[-1], ' is ', i, '\n')

[1.000000e+00 5.000000e-01 2.500000e-01 1.250000e-01 6.250000e-02
 3.125000e-02 1.562500e-02 7.812500e-03 3.906250e-03 1.953125e-03
 9.765625e-04]
Number of iterations to reach b =  0.0009765625  is  10 



## List comprehension example
List comprehensions allow us to express mathematical operations on sequences in a compact and readable form, which is particularly convenient in numerical and scientific Python code.

In [8]:
c = [(1 / i ** 2) for i in range(1, 5)]
print(c)
c_length = len(c)
print(c_length)

[1.0, 0.25, 0.1111111111111111, 0.0625]
4


## Function example
### Why use functions?

Functions allow us to **encapsulate logic**, **avoid code duplication**, and **make code easier to read and maintain**.  
Instead of repeatedly writing the same mathematical expressions, we define them once and reuse them consistently.

In numerical methods and scientific computing, functions are especially important because they:
- clearly represent mathematical models,
- make testing and modification easier,
- improve readability and reproducibility.


### What makes a good function?

A well-written function should:
- perform **one clearly defined task**,
- take all required data as **explicit arguments**,
- return its result without modifying global state,
- have a **descriptive name**,
- include a **short docstring** explaining what it does.

### Example: Particle motion under gravity

We consider a particle falling in a gravitational field.  
The analytical expressions for position and velocity are:

$
q(t) = q_0 + v_0 t - g t^2, \quad
v(t) = v_0 - g t
$

These expressions are implemented as two separate functions:

In [11]:
def pos(t, q0, v0, g):
    """Compute position given time, initial conditions, and gravity."""
    return q0 + v0 * t - g * t**2


def vel(t, v0, g):
    """Compute velocity given time, initial velocity, and gravity."""
    return v0 - g * t

Each function:
- implements exactly one formula,
- depends only on its inputs,
- returns a single well-defined quantity.


Let's start using these functions!
First we need to define initial values and parameters of the problem:

In [14]:
q0 = 10  # m, initial position
v0 = 10  # m/s, initial velocity
g = 9.81  # m/s^2, gravity

We now evaluate position and velocity at discrete time points and store the results.

In [13]:
N = 50
t = np.linspace(0, 10, N)
x = np.zeros((2, N))  # store position and velocity
for i in range(N):
    x[:, [i]] = np.array([[pos(t[i], q0, v0, g)],
                          [vel(t[i], v0, g)]])

### Key takeaway

Functions allow us to translate mathematical models into readable, reusable code.
This separation between model definition and numerical evaluation becomes essential once problems grow in complexity.